# First Play
- name: Play - Handle Files in all hosts
  hosts: all
  tasks:
  - name: all host are identified with a file
    copy:
      content: My family is {{ ansible_os_family }}
      dest: /family.txt
      mode: '777'
# Second play
- name: Play - for Alpines Nodejs app
  hosts: alpine-example-com
  tasks:
  - name: NodeJs is installed
    apk:
      name: "{{ item }}"
      update_cache: yes
      state: latest
    loop:
    - nodejs
    - nodejs-npm
  - name: app directory is created
    file:
      path: /node-app
      state: directory
  - name: app is installed
    template:
      src: app.js.j2
      dest: /node-app/app.js
  - name: app dependencies file is copied
    copy:
      src: package.json
      dest: /node-app/package.json
  - name: app dependencies are installed
    npm:
      path: /node-app
      state: present
      production: true
  - name: Install forever (to run Node.js app).
    npm: name=forever global=yes state=present
  
  - name: Check list of Node.js apps running.
    command: forever list
    register: forever_list
    changed_when: false

  - name: Start example Node.js app.
    command: forever start /node-app/app.js
    when: "forever_list.stdout.find('/node-app/app.js') == -1"



- name: Play - for RedHat based Hosts - Nginx
  hosts: redhat_group
  tasks:
  - name: yum repo exist
    copy:
      src: nginx.repo
      dest: /etc/yum.repos.d/nginx.repo

  - name: nginx is installed
    yum:
      name: nginx
      state: latest
      enablerepo: nginx
  - name: web server is started
    service:
      name: nginx
      state: started
      enabled: true
    ignore_errors: yes
  - name: smoke test
    uri:
      url: http://localhost
      return_content: yes